# VIRUS_NAME:
#   reference_name: needed in case of multi-chromosome viruses
#   ref_accessions:
#     - list
#     - of
#     - chromosome accessions (no extension) even if it's only one
#   primers: name of primers, no extension

virus: nCOV19_clinical_simulated


nCOV19_synthetic:
  reference_name: nCOV19_clinical_reference
  ref_accessions:
    - MN908947.3
  primers: artic_v3_all_alt
  has_alts: True
  need_singleton_extraction: False
  bioprojects:
    - PRJNA737419
  mem_mod: 0
  time_mod: 0


nCOV19_clinical_simulated_1:
  reference_name: nCOV19_clinical_reference
  consensus_set: nCOV19_clinical
  ref_accessions:
    - MN908947.3
  primers: artic_v3_all_alt
  c: 2000
  v: 20
  b: 1
  score_thresh: 16
  decay: 2
  drop_mean: 0.120
  drop_std: 0.100
  min_reads: 120_000
  max_reads: 220_000
  mem_mod: 0
  time_mod: 0


nCOV19_clinical_simulated_2:
  reference_name: nCOV19_clinical_reference
  consensus_set: nCOV19_clinical_2
  ref_accessions:
    - MN908947.3
  primers: artic_v3_all_alt
  c: 2000
  v: 20
  b: 1
  score_thresh: 16
  decay: 2
  drop_mean: 0.120
  drop_std: 0.100
  min_reads: 120_000
  max_reads: 220_000
  mem_mod: 0
  time_mod: 0


DENV1_simulated:
  reference_name: DENV1_reference
  consensus_set: DENV1
  ref_accessions:
    - NC_001477.1
  primers: DENV1_primers
  c: 400
  v: 400
  b: 1
  score_thresh: 12
  decay: 1.8
  drop_mean: 0.000
  drop_std: 0.000
  min_reads: 600_000
  max_reads: 1_100_000
  mem_mod: 1
  time_mod: 1

DENV2_simulated:
  reference_name: DENV2_reference
  consensus_set: DENV2
  ref_accessions:
    - NC_001474.2
  primers: DENV2_primers
  c: 200
  v: 200
  b: 1
  score_thresh: 12
  decay: 1.8
  drop_mean: 0.000
  drop_std: 0.000
  min_reads: 600_000
  max_reads: 1_100_000
  mem_mod: 1
  time_mod: 1

DENV3_simulated:
  reference_name: DENV3_reference
  consensus_set: DENV3
  ref_accessions:
    - NC_001475.2
  primers: DENV3_primers
  c: 200
  v: 200
  b: 1
  score_thresh: 12
  decay: 1.8
  drop_mean: 0.000
  drop_std: 0.000
  min_reads: 600_000
  max_reads: 1_100_000
  mem_mod: 1
  time_mod: 1

DENV4_simulated:
  reference_name: DENV4_reference
  consensus_set: DENV4
  ref_accessions:
    - NC_002640.1
  primers: DENV4_primers
  c: 200
  v: 200
  b: 1
  score_thresh: 12
  decay: 1.2
  drop_mean: 0.000
  drop_std: 0.000
  min_reads: 600_000
  max_reads: 1_100_000
  mem_mod: 1
  time_mod: 1