# VIRUS_NAME:
#   reference_name: needed in case of multi-chromosome viruses
#   ref_accessions:
#     - list
#     - of
#     - chromosome accessions (no extension) even if it's only one
#   primers: name of primers, no extension

virus: nCOV19_clinical_simulated
cli_v: "empty"
cli_c: "empty"
cli_b: "empty"
cli_decay: "empty"
frac: "empty"
denom: 4


nCOV19_synthetic_simulated:
  reference_name: nCOV19_clinical_reference
  consensus_set: nCOV19_synthetic
  ref_accessions:
    - MN908947.3
  primers: artic_v3_all_alt
  c: 150
  v: 1
  b: 1
  score_thresh: 16
  decay: 1
  # pcr_err: -ins 0.00001 -del 0.0000625 -subs 0.0012425 -rins 0.00001 -rdel 0 -rsubs 0.0016785 -dl 0.345 -il 3
  pcr_err: --no_pcr_errors
  min_reads: 60_000
  max_reads: 300_000
  mem_mod: 0
  time_mod: 0


nCOV19_clinical_simulated_1:
  reference_name: nCOV19_clinical_reference
  consensus_set: nCOV19_clinical
  ref_accessions:
    - MN908947.3
  primers: artic_v3_all_alt
  c: 150
  v: 1
  b: 1
  score_thresh: 16
  decay: 1
  # pcr_err: -ins 0.00001 -del 0.0000625 -subs 0.0012425 -rins 0.00001 -rdel 0 -rsubs 0.0016785 -dl 0.345 -il 3
  pcr_err: --no_pcr_errors
  min_reads: 120_000
  max_reads: 220_000
  mem_mod: 0
  time_mod: 0


nCOV19_clinical_simulated_2:
  reference_name: nCOV19_clinical_reference
  consensus_set: nCOV19_clinical_2
  ref_accessions:
    - MN908947.3
  primers: artic_v3_all_alt
  c: 150 # 200
  v: 1
  b: 1
  score_thresh: 16
  decay: 1
  # pcr_err: -ins 0.000005 -del 0.00003125 -subs 0.00062125 -rins 0.000005 -rdel 0 -rsubs 0.00083925 -dl 0.1725 -il 2
  pcr_err: --no_pcr_errors
  min_reads: 120_000
  max_reads: 220_000
  mem_mod: 0
  time_mod: 0


DENV1_simulated:
  reference_name: DENV1_reference
  consensus_set: DENV1
  ref_accessions:
    - NC_001477.1
  primers: DENV1_primers
  c: 400
  v: 1
  b: 1
  score_thresh: 12
  decay: 0.1
  pcr_err: --no_pcr_errors
  min_reads: 600_000
  max_reads: 1_100_000
  mem_mod: 1
  time_mod: 1

DENV2_simulated:
  reference_name: DENV2_reference
  consensus_set: DENV2
  ref_accessions:
    - NC_001474.2
  primers: DENV2_primers
  c: 400
  v: 1
  b: 1
  score_thresh: 12
  decay: 0.1
  pcr_err: --no_pcr_errors
  min_reads: 300_000
  max_reads: 650_000
  mem_mod: 1
  time_mod: 1

DENV3_simulated:
  reference_name: DENV3_reference
  consensus_set: DENV3
  ref_accessions:
    - NC_001475.2
  primers: DENV3_primers
  c: 400
  v: 1
  b: 1
  score_thresh: 12
  decay: 0.1
  pcr_err: --no_pcr_errors
  min_reads: 600_000
  max_reads: 1_100_000
  mem_mod: 1
  time_mod: 1

DENV4_simulated:
  reference_name: DENV4_reference
  consensus_set: DENV4
  ref_accessions:
    - NC_002640.1
  primers: DENV4_primers
  c: 400
  v: 1
  b: 1
  score_thresh: 12
  decay: 0.1
  pcr_err: --no_pcr_errors
  min_reads: 600_000
  max_reads: 1_100_000
  mem_mod: 1
  time_mod: 1